apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-collector-deployment
spec:
  selector:
    matchLabels:
      app: jaeger-collector
  replicas: 2
  template:
    metadata:
      labels:
        app: jaeger-collector
    spec:
      nodeSelector:
        AppGroup: {{ .Values.nodeGroup }}
      containers:
        - name: jaeger-collector-container
          image: jaegertracing/jaeger-collector
          args:
            - "--cassandra.keyspace=jaeger_v1_dc1"
            - "--cassandra.servers=cassandra"
            - "--collector.zipkin.host-port=9411"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "/"
              port: 14269
          ports:
            - name: "port14268"
              containerPort: 14268
            - name: "port9411"
              containerPort: 9411
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  selector:
    app: jaeger-collector
  type: NodePort
  ports:
    - name: "port14268"
      protocol: TCP
      port: 14268
      targetPort: "port14268"
    - name: "port9411"
      protocol: TCP
      port: 9411
      targetPort: "port9411"
