apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger-query-ui
    labels:
      app: jaeger-query-ui
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaeger-query-ui
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger-query-ui
      spec:
        containers:
        - image: jaegertracing/jaeger-query:1.9.0
          name: jaeger-query-ui
          args:
          - "--cassandra.servers=cassandra"
          - "--cassandra.keyspace=jaeger_v1_dc1"
          ports:
          - name: "port"
            containerPort: 16686
            protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 16687
- apiVersion: v1
  kind: Service
  metadata:
    name: jaeger-query-ui
    labels:
      app: jaeger-query-ui
  spec:
    selector:
      app: jaeger-query-ui
    type: NodePort
    ports:
    - name: "port"
      port: 80
      targetPort: "port"
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: jaeger-query-proxy
    labels:
      app: jaeger-query-proxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: jaeger-query-proxy
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: jaeger-query-proxy
      spec:
        containers:
        - image: quay.io/dtan4/nginx-basic-auth-proxy
          name: jaeger-query-proxy
          ports:
          - containerPort: 80
          env:
          - name: BASIC_AUTH_USERNAME
            value: "jaeger"
          - name: BASIC_AUTH_PASSWORD
            value: {{ .Values.jaegerQueryPassword | quote }}
          - name: PROXY_PASS
            value: "http://jaeger-query-ui"