apiVersion: v1
kind: Service
metadata:
  labels:
    name: verdaccio
  name: verdaccio
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  ports:
    - port: 80
      targetPort: 4873
  type: NodePort
  selector:
    app: verdaccio