# Works together with Frever.Impersonate CLI util to generate tokens.
# Supports both local and remote environment
# Works together with Frever.Impersonate CLI util to generate tokens.
# Supports both local and remote environment
@version=latest
@env=content-prod

@auth_server=https://{{env}}.frever-api.com/{{version}}/auth/
@asset_server=https://{{env}}.frever-api.com/{{version}}/asset/
@admin_server=https://{{env}}.frever-api.com/{{version}}/admin/
@client_server=https://{{env}}.frever-api.com/{{version}}/client/
@video_server=https://{{env}}.frever-api.com/{{version}}/video/
@notification_server=https://{{env}}.frever-api.com/{{version}}/notification/
@token_dev_16=xxxxxxxxx
@token_stage_326670=xxxxxxxxx
@token_prod_1877=xxxxxxxxx
@token={{token_prod_1877}}

##
# @auth_server=http://localhost:5002/
# @asset_server=http://localhost:5004/file-storage/
# @admin_server=http://localhost:5010/admin/
# @client_server=http://localhost:5011/client/
# @video_server=http://localhost:5005/video/
# @notification_server=http://localhost:5008/notification/
# @token_dev_16=xxxxxxxxx
# @token_stage_32312=xxxxxxxxx
# @token={{token_stage_32312}}

### Request should be blocked
POST {{auth_server}}account/RegisterTemporaryAccount
Content-Type: application/json
X-Device-Id: 3BA1BADD-567B-4E37-A4A9-FDE0D6791996

{
  "birthDate": "1999-01-01",
  "country": "swe",
  "defaultLanguage": "swe"
}

### Request should be allowed
POST {{auth_server}}account/RegisterTemporaryAccount
Content-Type: application/json

{
  "birthDate": "1999-01-01",
  "country": "swe",
  "defaultLanguage": "swe"
}

### Request should be allowed
POST {{auth_server}}/account/RegisterTemporaryAccount
Content-Type: application/json

{
  "birthDate": "1999-01-01",
  "country": "swe",
  "defaultLanguage": "swe"
}

### Request should be allowed
POST {{auth_server}}/account/RegisterTemporaryAccount
Content-Type: application/json
X-Device-Id: anyalloweddevice

{
  "birthDate": "1999-01-01",
  "country": "swe",
  "defaultLanguage": "swe"
}

### Authenticate
# @name auth
POST {{auth_server}}connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=xxxxxxxxx&password=123456&client_id=Server&scope=friends_factory.creators_api+offline_access&client_secret=xxxxxxxxx


###
@token={{auth.response.body.access_token}}

###
GET {{admin_server}}api/device-blacklist?search=xx&take=10&skip=0
Authorization: Bearer {{token}}

###
POST {{admin_server}}api/device-blacklist
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "axxx-xxssd-xx",
  "reason": "test"
}

###
DELETE {{admin_server}}api/device-blacklist
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "deviceId": "axxx-xxssd-xx"
}
