alter table jaeger_v1_dc1.duration_index with default_time_to_live = 604800;
alter table jaeger_v1_dc1.operation_names_v2 with default_time_to_live = 604800;
alter table jaeger_v1_dc1.service_name_index with default_time_to_live = 604800;
alter table jaeger_v1_dc1.service_names with default_time_to_live = 604800;
alter table jaeger_v1_dc1.service_operation_index with default_time_to_live = 604800;
alter table jaeger_v1_dc1.tag_index with default_time_to_live = 604800;
alter table jaeger_v1_dc1.traces with default_time_to_live = 604800;