output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_arn" {
  value = module.eks.cluster_iam_role_arn
}

output "fargate_iam_role_arn" {
  value = module.eks.fargate_iam_role_arn
}

output "worker_iam_role_arn" {
  value = module.eks.worker_iam_role_arn
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  value = module.eks.config_map_aws_auth
}

output "region" {
  value = var.region
}

output "cluster_name" {
  value = var.env
}

output "ssl_certificate_arn" {
  value = data.aws_acm_certificate.issued.arn
}

output "auth_docker_repository_url" {
  value = module.auth_service.docker_repository_url
}

output "notification_docker_repository_url" {
  value = module.notification_service.docker_repository_url
}

output "asset_docker_repository_url" {
  value = module.asset_service.docker_repository_url
}

output "main_docker_repository_url" {
  value = module.main_service.docker_repository_url
}

output "assetmanager_docker_repository_url" {
  value = module.assetmanager_service.docker_repository_url
}

output "video_docker_repository_url" {
  value = module.video_service.docker_repository_url
}

output "social_docker_repository_url" {
  value = module.social_service.docker_repository_url
}

output "appservice_repository_url" {
  value = aws_ecr_repository.appservice.repository_url
}

output "cdn_domain" {
  value = "${var.env}.frever-content.com"
}

output "cloudfront_distribution_id" {
  value = module.cdn.cloudfront_distribution_id
}

output "redis_host" {
  value = aws_elasticache_cluster.redis.cache_nodes[0].address
}

output "db_address" {
  value = var.createDb ? aws_db_instance.db[0].address : ""
}

output "db_user_name" {
  value = var.db_user_name
}

output "db_password" {
  value = var.db_password
}


output "cluster_worker_iam_role_name" {
  value = module.eks.worker_iam_role_name
}

output "video-conversion-job-creation-sqs-queue" {
  value = aws_sqs_queue.video-conversion-job-creation.id
}

output "video-conversion-job-creator-lambda" {
  value = aws_lambda_function.video-conversion-job-creator.function_name
}
