# Works together with Frever.Impersonate CLI util to generate tokens.
# Supports both local and remote environment
@version=latest
@env=content-prod

@ml=https://localhost.localdomain:8811/
@ml=http://localhost.localdomain:8183/

@auth_server=https://{{env}}.frever-api.com/{{version}}/auth/
@asset_server=https://{{env}}.frever-api.com/{{version}}/asset/
@admin_server=https://{{env}}.frever-api.com/{{version}}/admin/
@client_server=https://{{env}}.frever-api.com/{{version}}/client/
@video_server=https://{{env}}.frever-api.com/{{version}}/video/
@notification_server=https://{{env}}.frever-api.com/{{version}}/notification/
@token_dev_16=xxxxxxxxx
@token_prod_21347=xxxxxxxxx
@token_prod_432=xxxxxxxxx
@token_prod_102275=xxxxxxxxx
@token_stage_899=xxxxxxxxx
@token={{token_stage_899}}


###
@auth_server=http://localhost:5002/
@asset_server=http://localhost:5004/file-storage/
@admin_server=http://localhost:5010/admin/
@client_server=http://localhost:5011/client/
@video_server=http://localhost:5005/video/
@notification_server=http://localhost:5008/notification/
@token_prod_432=xxxxxxxxx
@token_stage_16=xxxxxxxxx
@token_prod_102275=xxxxxxxxx
@token_stage_32312=xxxxxxxxx
@token={{token_stage_32312}}


############ END ##############


### Generate feed due this request
GET {{client_server}}api/start-pack/default-user-assets
Authorization: Bearer {{token}}
# Accept: application/vnd.google.protobuf

###
# @name fyp2
GET {{video_server}}video/fyp-v2?$take=20
Authorization: Bearer {{token}}
# Accept: application/vnd.google.protobuf

### Force refresh
# @name fyp2
GET {{video_server}}video/fyp-v2?$take=20&refresh
Authorization: Bearer {{token}}
# Accept: application/vnd.google.protobuf

###
POST {{admin_server}}api/cache/reset
Authorization: Bearer {{token}}

###
GET {{video_server}}video/my-videos
Authorization: Bearer {{token}}

###
GET {{video_server}}video/template
Authorization: Bearer {{token}}


###
GET {{video_server}}video/my-videos
    ?$targetVideo=4743
    &$takeNext=3
    &$takePrevious=3
Authorization: Bearer {{token}}


###
GET {{video_server}}video/by-group/1863
Authorization: Bearer {{token}}

###
GET {{video_server}}video/by-group/1863
    ?$takeNext=10000
Authorization: Bearer {{token}}

###
GET {{ml}}api/feed-recsys/recommend?groupId=2951&lat=23.22&lon=23.21
X-Frever-Experiments: ml_feed_following_2=treatment
Host: frever-ml.com