@auth_server=http://localhost:5002
@auth_server=https://content-stage.frever-api.com/latest/auth
# @auth_server=https://content-stage.frever-api.com/latest/auth
# @auth_server=https://content-prod.frever-api.com/latest/auth


### Authenticate
# @name auth
POST {{auth_server}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=xxxxxxxxx&password=123456&client_id=Server&scope=friends_factory.creators_api+offline_access&client_secret=xxxxxxxxx

###
POST {{auth_server}}/api/verify-phone-number
Content-Type: application/json

{
  "phoneNumber": "xxxxxxxxx"
}

### Authenticate
# @name auth
POST {{auth_server}}/connect/token
Content-Type: application/x-www-form-urlencoded

phone_number=xxxxxxxxx&verification_token=223149&grant_type=phone_number_token&client_id=Server&scope=friends_factory.creators_api&client_secret=xxxxxxxxx

###
POST {{auth_server}}/api/verify-email
Content-Type: application/json

{
  "email": "xxxxxxxxx"
}

### Authenticate
# @name auth
POST {{auth_server}}/connect/token
Content-Type: application/x-www-form-urlencoded

verification_token=904290&email=xxxxxxxxx&grant_type=email_auth_token&client_id=Server&scope=friends_factory.creators_api+offline_access&client_secret=xxxxxxxxx

###
@asset_server={{auth.response.body.asset_server}}
@main_server={{auth.response.body.server_url}}
@admin_server={{auth.response.body.assetmanager_server}}
@chat_server={{auth.response.body.chat_server}}
@client_server={{auth.response.body.client_server}}
@video_server={{auth.response.body.video_server}}
@notification_server={{auth.response.body.notification_server}}

### HEALTHCHECKS
GET {{auth_server}}/api/health

###
GET {{auth_server}}/.well-known/openid-configuration

###
GET {{auth_server}}/api/Client/SupportedVersions

###
POST {{admin_server}}api/cache/reset
Authorization: Bearer {{auth.response.body.access_token}}

### AUTH SERVER

### Registration with email
# @name auth
POST {{auth_server}}/account/register
Content-Type: application/json

{
  "email": "xxxxxxxxx",
  "verificationCode": "362331",
  "userName": "null",
  "birthDate": "2001-01-01",
  "analyticsEnabled": true
}

### Registration with email
# @name auth
POST {{auth_server}}/account/RegisterTemporaryAccount
Content-Type: application/json

{
  "birthDate": "2015-01-01",
  "country": "swe",
  "defaultLanguage": "swe"
}

### Update data
# @name auth1
POST {{auth_server}}/account/UpdateAccount
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "password": "testthismess",
  "userName": "testthismess1111",
  "email": null
}

###
POST {{auth_server}}/account/ValidateLoginInfo
Content-Type: application/json

{
  "email": null,
  "userName": "test",
  "phoneNumber": null
}

###
POST {{auth_server}}/account/ValidateRegistrationInfo
Content-Type: application/json

{
  "email": null,
  "userName": "test",
  "phoneNumber": null
}


### ADMIN SERVER

###
GET {{admin_server}}api/crew/moderation?$top=5&$filter=chatId eq 1
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{admin_server}}api/video/moderation?$top=10
Authorization: Bearer {{auth.response.body.access_token}}

###
DELETE {{admin_server}}api/account/moderation/3002/hard-delete
Authorization: Bearer {{auth.response.body.access_token}}

### VIDEO SERVER

###
GET {{video_server}}video/fyp-v2
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/trending?$targetVideo=&$takeNext=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/hashtag/27?$targetVideo=&$takeNext=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/template/191?$targetVideo=&$takeNext=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/sound/116/song?$targetVideo=&$takeNext=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/by-task/111?$targetVideo=&$takeNext=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/tagged/512?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/7928/remixes?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/featured?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{video_server}}video/my-friends-videos?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/my-following?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/by-group/1915/tasks?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/by-group/1865?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/my-videos?$targetVideo=&$takeNext=5&$takePrevious=5
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf


@videoId=7935

###
GET {{video_server}}video/{{videoId}}
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/{{videoId}}/view
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/watch/corGga4gekGqahcsGG1wA
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{video_server}}video/{{videoId}}/comment
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
POST {{video_server}}video/{{videoId}}/like
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{video_server}}video/{{videoId}}/unlike
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{video_server}}video/{{videoId}}/comment
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "Text": "Test comment"
}

###
# @name myVideo
GET {{video_server}}video/my-videos
Authorization: Bearer {{auth.response.body.access_token}}

###
DELETE {{video_server}}video/{{myVideo.response.body.$[0].id}}
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{video_server}}video/1765/access
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "access": 0,
  "taggedFriendIds": [2534]
}


# -- uploading video --

###
# @name initUploading
POST {{video_server}}video/upload
Authorization: Bearer {{auth.response.body.access_token}}

###
# @name upload video
PUT {{initUploading.response.body.uploadUrl}}

< ./Server/Server.Api/Http/video.mp4

###
# @name completeUploading
PUT {{video_server}}video/upload/{{initUploading.response.body.uploadId}}
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "levelId": 195530,
    "size": 10318854,
    "durationSec": 7,
    "access": 3,
    "videoOrientation": 1,
    "taggedFriendIds": [2534]
}

###
PUT {{video_server}}video/upload-non-level/{{initUploading.response.body.uploadId}}
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "size": 10318854,
    "durationSec": 7,
    "access": 3,
    "videoOrientation": 1
}

### CLIENT

###
GET {{client_server}}api/group/top?nickname=ph&top=20
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/group/1915
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/group/16/friends
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{client_server}}api/group/16/follower
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{client_server}}api/group/16/following
Authorization: Bearer {{auth.response.body.access_token}}

### Follow
POST {{client_server}}api/group/1915/follower
Authorization: Bearer {{auth.response.body.access_token}}

### Unfollow
DELETE {{client_server}}api/group/2534/follower
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{client_server}}api/me
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/task
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/template
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/level/drafts?take=20&skip=0
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/editor-settings/by-task/17
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{client_server}}api/start-pack/metadata
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/start-pack/pre-fetch
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/start-pack/default-user-assets
Authorization: Bearer {{auth.response.body.access_token}}
#Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/gamification/current-season
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
GET {{client_server}}api/localization/por
Authorization: Bearer {{auth.response.body.access_token}}
x-localization-version: 3ed2ee1c62b7f02b2a9775f052a6b3b6

### NOTIFICATIONS

###
# @name myNotifications
GET {{notification_server}}api/notifications?$top=20
Authorization: Bearer {{auth.response.body.access_token}}
# Accept: application/vnd.google.protobuf

###
PUT {{notification_server}}api/notifications/mark-as-read
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type:  application/json

[
  {{myNotifications.response.body.$[0].id}}
]


###
# @name uploadMainFile
GET {{asset_server}}api/File/PreUploadingUrl
Authorization: Bearer {{auth.response.body.access_token}}

###
PUT {{uploadMainFile.response.body.$.uploadUrl}}

< ./test-files/peakpx-6.jpg

###
# @name uploadThumbnail128
GET {{asset_server}}api/File/PreUploadingUrl
Authorization: Bearer {{auth.response.body.access_token}}

###
PUT {{uploadThumbnail128.response.body.$.uploadUrl}}

< ./test-files/peakpx-6-2.jpg

###
POST {{admin_server}}api/SetLocationBackground
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
  "name": "Test2",
  "files": [
    {
      "file": 0,
      "resolution": null,
      "subType": null,
      "version": null,
      "extension": "Jpg",
      "state": 0,
      "source": {
          "uploadId": "{{uploadMainFile.response.body.$.uploadId}}",
          "copyFrom": null
      }
    },
    {
        "file": 1,
        "resolution": "128x128",
        "subType": null,
        "version": null,
        "extension": "Jpg",
        "state": 0,
        "source": {
            "uploadId": "{{uploadThumbnail128.response.body.$.uploadId}}",
            "copyFrom": null
        }
    }
  ]
}

### ASSET SERVER

@assetType=BodyAnimation

###
# @name asset
GET {{admin_server}}api/{{@assetType}}
Authorization: Bearer {{auth.response.body.access_token}}

###
@assetId=798
@assetVersion=20240122T163856U6108c345fd5e4c3bbafbfd04c0c11e3c
@assetResolution=128x128

###
GET {{asset_server}}api/Cdn/{{assetType}}/{{assetId}}/Thumbnail/{{assetResolution}}/{{assetVersion}}
# Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{asset_server}}api/Cdn/{{assetType}}/{{assetId}}/MainFile/iOS/{{assetVersion}}
Authorization: Bearer {{auth.response.body.access_token}}

[
  {
    "source":{
      "uploadId":"9b3de307-8f1c-43ac-8736-462b855d5edd"
      },
    "version":"20240122T163856U6108c345fd5e4c3bbafbfd04c0c11e3c",
    "file":"Thumbnail",
    "extension":"Png",
    "resolution":"128x128"
  },
  {
    "source":{
      "uploadId":"3264a744-437a-4c14-91ca-b46512003378"
    },
    "version":"20240122T163856U34a75b047d664af9bc3625003c6a3771",
    "file":"Thumbnail",
    "extension":"Png",
    "resolution":"256x256"
  },
  {
    "source":{
      "uploadId":"31cb9733-008b-4eb5-9e7a-3a5d7ff1d67c"
    },
    "version":"20240122T163856Ued4f0b9d04e7463aa1b8dd5b80914bd2",
    "file":"Thumbnail",
    "extension":"Png",
    "resolution":"512x512"
  },
  {
    "source":{
      "uploadId":"831fba05-0916-461f-978b-d3f2c703791b"
    },
    "version":"20240122T163856U656bf9e41b5646f19bbe90d20ddbf7ed",
    "file":"Thumbnail",
    "extension":"Png",
    "resolution":"1600x900"
  }
]

###
GET {{client_server}}api/level/drafts?take=20&skip=0
Authorization: Bearer xxxxxxxxx