# Works together with Frever.Impersonate CLI util to generate tokens.
# Supports both local and remote environment
@version=latest
@env=dev-1

@auth_server=https://{{env}}.frever-api.com/{{version}}/auth/
@asset_server=https://{{env}}.frever-api.com/{{version}}/asset/
@admin_server=https://{{env}}.frever-api.com/{{version}}/admin/
@client_server=https://{{env}}.frever-api.com/{{version}}/client/
@video_server=https://{{env}}.frever-api.com/{{version}}/video/
@notification_server=https://{{env}}.frever-api.com/{{version}}/notification/
@token=xxxxxxxxx



###
@auth_server=http://localhost:5002/
@asset_server=http://localhost:5004/file-storage/
@admin_server=http://localhost:5010/admin/
@client_server=http://localhost:5011/client/
@video_server=http://localhost:5005/video/
@notification_server=http://localhost:5008/notification/
@token=xxxxxxxxx


############ END ##############

###
POST {{auth_server}}api/verify-email
Content-Type: application/json

{
  "email": "xxxxxxxxx"
}


### Registration with email
POST {{auth_server}}account/register
Content-Type: application/json

{
  "email": "xxxxxxxxx",
  "verificationCode": "xxxxxxxxx",
  "userName": "xxxxxxxxx",
  "birthDate": "xxxxxxxxx",
  "analyticsEnabled": true,
  "defaultLanguage": "eng",
  "country": "swe"
}

###
GET {{client_server}}api/me
Authorization: Bearer {{token}}


###
GET {{client_server}}api/group/2636
Authorization: Bearer {{token}}

###
PATCH {{client_server}}api/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "bio": "Software dw",
  "bioLinks": {
    "instagram": "xxxxxxxxx",
    "facebook": "xxxxxxxxx"
  }
}

###
GET {{client_server}}api/group/top
Authorization: Bearer {{token}}

###
GET {{admin_server}}api/UserSound
Authorization: Bearer {{token}}
