apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: NAMESPACE_NAME
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/CLUSTER_NAME/secrets/auth-certificate"
        objectType: "ssmparameter"
        objectAlias: authCertificateAlias
      - objectName: "/CLUSTER_NAME/secrets/auth-certificatePassword"
        objectType: "ssmparameter"
        objectAlias: authCertificatePasswordAlias
      - objectName: "/CLUSTER_NAME/secrets/auth-clientSecret"
        objectType: "ssmparameter"
        objectAlias: authClientSecretAlias
      - objectName: "/CLUSTER_NAME/secrets/google-api-key"
        objectType: "ssmparameter"
        objectAlias: googleApiKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/cs-auth"
        objectType: "ssmparameter"
        objectAlias: csAuthAlias
      - objectName: "/CLUSTER_NAME/secrets/cs-main"
        objectType: "ssmparameter"
        objectAlias: csMainAlias
      - objectName: "/CLUSTER_NAME/secrets/cs-main-replica"
        objectType: "ssmparameter"
        objectAlias: csMainReplicaAlias
      - objectName: "/CLUSTER_NAME/secrets/cs-video"
        objectType: "ssmparameter"
        objectAlias: csVideoAlias
      - objectName: "/CLUSTER_NAME/secrets/oneSignal-apiKey"
        objectType: "ssmparameter"
        objectAlias: oneSignalApiKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/oneSignal-appId"
        objectType: "ssmparameter"
        objectAlias: oneSignalAppIdAlias
      - objectName: "/CLUSTER_NAME/secrets/twilio-messagingServiceSid"
        objectType: "ssmparameter"
        objectAlias: twilioMessagingServiceSidAlias
      - objectName: "/CLUSTER_NAME/secrets/twilio-secret"
        objectType: "ssmparameter"
        objectAlias: twilioSecretAlias
      - objectName: "/CLUSTER_NAME/secrets/twilio-sid"
        objectType: "ssmparameter"
        objectAlias: twilioSidAlias
      - objectName: "/CLUSTER_NAME/secrets/twilio-verifyServiceSid"
        objectType: "ssmparameter"
        objectAlias: twilioVerifyServiceSidAlias
      - objectName: "/CLUSTER_NAME/secrets/data-protector-key"
        objectType: "ssmparameter"
        objectAlias: dataProtectorKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/music-provider-oauth-consumer-key"
        objectType: "ssmparameter"
        objectAlias: musicProviderOAuthConsumerKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/music-provider-oauth-consumer-secret"
        objectType: "ssmparameter"
        objectAlias: musicProviderOAuthConsumerSecretAlias
      - objectName: "/CLUSTER_NAME/secrets/hive-text-moderation-key"
        objectType: "ssmparameter"
        objectAlias: hiveTextModerationKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/hive-visual-moderation-key"
        objectType: "ssmparameter"
        objectAlias: hiveVisualModerationKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/blokur-apiToken"
        objectType: "ssmparameter"
        objectAlias: blokurApiTokenAlias
      - objectName: "/CLUSTER_NAME/secrets/apps-flyer-token"
        objectType: "ssmparameter"
        objectAlias: appsFlyerTokenAlias
      - objectName: "/CLUSTER_NAME/secrets/stableDiffusion-apiKey"
        objectType: "ssmparameter"
        objectAlias: stableDiffusionApiKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/replicate-apiKey"
        objectType: "ssmparameter"
        objectAlias: replicateApiKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/klingAccessKey"
        objectType: "ssmparameter"
        objectAlias: klingAccessKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/klingSecretKey"
        objectType: "ssmparameter"
        objectAlias: klingSecretKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/pixVerseApiKey"
        objectType: "ssmparameter"
        objectAlias: pixVerseApiKeyAlias
      - objectName: "/CLUSTER_NAME/secrets/appStoreIssuerId"
        objectType: "ssmparameter"
        objectAlias: appStoreIssuerIdAlias
      - objectName: "/CLUSTER_NAME/secrets/appStoreKeyData"
        objectType: "ssmparameter"
        objectAlias: appStoreKeyDataAlias
      - objectName: "/CLUSTER_NAME/secrets/appStoreKeyId"
        objectType: "ssmparameter"
        objectAlias: appStoreKeyIdAlias
      - objectName: "/CLUSTER_NAME/secrets/appStoreSharedSecret"
        objectType: "ssmparameter"
        objectAlias: appStoreSharedSecretAlias
  secretObjects:
    - secretName: ssm-secrets
      type: Opaque
      data:
        - objectName: authCertificateAlias
          key: auth.certificate
        - objectName: authCertificatePasswordAlias
          key: auth.certificatePassword
        - objectName: authClientSecretAlias
          key: auth.clientSecret
        - objectName: googleApiKeyAlias
          key: google.apiKey
        - objectName: csAuthAlias
          key: cs.auth
        - objectName: csMainAlias
          key: cs.main
        - objectName: csMainReplicaAlias
          key: cs.main.replica
        - objectName: csVideoAlias
          key: cs.video
        - objectName: oneSignalApiKeyAlias
          key: oneSignal.apiKey
        - objectName: oneSignalAppIdAlias
          key: oneSignal.appId
        - objectName: twilioMessagingServiceSidAlias
          key: twilio.messagingServiceSid
        - objectName: twilioSecretAlias
          key: twilio.secret
        - objectName: twilioSidAlias
          key: twilio.sid
        - objectName: twilioVerifyServiceSidAlias
          key: twilio.verifyServiceSid
        - objectName: dataProtectorKeyAlias
          key: data.protector.key
        - objectName: musicProviderOAuthConsumerKeyAlias
          key: musicProvider.OAuth.consumerKey
        - objectName: musicProviderOAuthConsumerSecretAlias
          key: musicProvider.OAuth.consumerSecret
        - objectName: hiveTextModerationKeyAlias
          key: hive.text.moderation.key
        - objectName: hiveVisualModerationKeyAlias
          key: hive.visual.moderation.key
        - objectName: blokurApiTokenAlias
          key: blokur.apiToken
        - objectName: appsFlyerTokenAlias
          key: appsFlyer.token
        - objectName: stableDiffusionApiKeyAlias
          key: stableDiffusion.apiKey
        - objectName: replicateApiKeyAlias
          key: replicate.apiKey
        - objectName: klingAccessKeyAlias
          key: kling.accessKey
        - objectName: klingSecretKeyAlias
          key: kling.secretKey
        - objectName: pixVerseApiKeyAlias
          key: pixVerse.apiKey
        - objectName: appStoreIssuerIdAlias
          key: appStore.issuerId
        - objectName: appStoreKeyDataAlias
          key: appStore.keyData
        - objectName: appStoreKeyIdAlias
          key: appStore.keyId
        - objectName: appStoreSharedSecretAlias
          key: appStore.sharedSecret
