{
 "title": "Cluster Info",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Node Pressure",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max_over_time( kube_node_status_condition {condition!=\"Ready\"}[1m]) > 0  "
    }
   ]
  },
  {
   "title": "Node Disk Free Space",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min by (kubernetes_node) (node_filesystem_avail_bytes/1024/1024/1024)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage %",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100-(node_memory_MemFree_bytes/ node_memory_MemTotal_bytes)*100",
     "legendFormat": "{{kubernetes_node}}"
    }
   ]
  },
  {
   "title": "Container CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (container) (rate(container_cpu_usage_seconds_total{ namespace=\"content-stage\", container!=\"POD\",container!=\"\" }[5m]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Avg Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_alb_active_connection_count_average{tag_kubernetes_io_namespace=\"content-stage\"}",
     "legendFormat": "{{tag_kubernetes_io_ingress_name}}"
    }
   ]
  },
  {
   "title": "ALB 5XX (Target and ELB)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tag_kubernetes_io_ingress_name) (rate( aws_alb_httpcode_target_5_xx_count_sum{tag_kubernetes_io_namespace=\"content-stage\"}[5m]))",
     "legendFormat": "{{tag_kubernetes_io_ingress_name}}"
    },
    {
     "expr": "sum by (tag_kubernetes_io_ingress_name) (rate( aws_alb_httpcode_elb_5_xx_count_sum{tag_kubernetes_io_namespace=\"content-stage\"}[5m]))",
     "legendFormat": "{{tag_kubernetes_io_ingress_name}}"
    }
   ]
  }
 ]
}