# Works together with Frever.Impersonate CLI util to generate tokens.
# Supports both local and remote environment
@version=latest
@env=dev-1

@auth_server=https://{{env}}.frever-api.com/{{version}}/auth/
@asset_server=https://{{env}}.frever-api.com/{{version}}/asset/
@admin_server=https://{{env}}.frever-api.com/{{version}}/admin/
@client_server=https://{{env}}.frever-api.com/{{version}}/client/
@video_server=https://{{env}}.frever-api.com/{{version}}/video/
@notification_server=https://{{env}}.frever-api.com/{{version}}/notification/
@token=xxxxxxxxx

###
# @auth_server=http://localhost:5002/
# @asset_server=http://localhost:5004/file-storage/
# @admin_server=http://localhost:5010/admin/
# @client_server=http://localhost:5011/client/
# @video_server=http://localhost:5005/video/
# @notification_server=http://localhost:5008/notification/
# @token=xxxxxxxxx

############ END ##############


###
DELETE {{admin_server}}api/music/moderation/audio?userSoundId=78
Authorization: Bearer {{token}}

###
POST {{admin_server}}api/music/moderation/audio?userSoundId=78
Authorization: Bearer {{token}}


###
POST {{admin_server}}api/music/moderation/fill-up-missing-isrc
Authorization: Bearer {{token}}

###
GET {{admin_server}}api/usersound/406
Authorization: Bearer {{token}}

###
PATCH {{admin_server}}api/usersound
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "id": 406,
  "name": "1testdevestated 11"
}
