@auth_server=http://localhost:5002
# @auth_server=https://dev.frever-api.com/latest/auth
# @auth_server=https://content-stage.frever-api.com/latest/auth

### Authenticate
# @name auth
POST {{auth_server}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&username=xxxxxxxxx&password=123456&client_id=Server&scope=friends_factory.creators_api+offline_access&client_secret=xxxxxxxxx

###
@admin_server={{auth.response.body.assetmanager_server}}

###
POST {{admin_server}}api/cache/reset
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{admin_server}}api/role/moderation/access-scope
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{admin_server}}api/role/moderation/role
Authorization: Bearer {{auth.response.body.access_token}}

###
GET {{admin_server}}api/role/moderation/user
Authorization: Bearer {{auth.response.body.access_token}}

###
POST {{admin_server}}api/role/moderation/role
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "id": 0,
    "name": "test-role",
    "accessScopes": []
}

###
POST {{admin_server}}api/role/moderation/user
Authorization: Bearer {{auth.response.body.access_token}}
Content-Type: application/json

{
    "email": "xxxxxxxxx",
    "roleIds": [1]
}