output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "cluster_iam_role_arn" {
  value = module.eks.cluster_iam_role_arn
}

output "fargate_iam_role_arn" {
  value = module.eks.fargate_iam_role_arn
}

output "worker_iam_role_arn" {
  value = module.eks.worker_iam_role_arn
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  value = module.eks.config_map_aws_auth
}

output "region" {
  value = var.region
}

output "cluster_name" {
  value = var.env
}

output "ssl_certificate_arn" {
  value = data.aws_acm_certificate.issued.arn
}

output "cluster_worker_iam_role_name" {
  value = module.eks.worker_iam_role_name
}


